ut_input:
	g++ -g -std=c++11 Input.cpp ut_Input.cpp -o ut_input

ut_in_out:
	g++ -g-std=c++11 Input.cpp Output.cpp ut_in_out.cpp -o ut_in_out

ut_abs:
	g++ -g -std=c++11 -pthread Input.cpp Output.cpp Abstract.cpp ut_abs.cpp -o ut_abs

ut_logger:
	g++ -g -std=c++11 -pthread Input.cpp Output.cpp Abstract.cpp Logger.cpp ut_logger.cpp -o ut_logger

benchmark:
	g++ -g -std=c++11 -pthread Input.cpp Output.cpp Abstract.cpp Logger.cpp benchmark.cpp -o benchmark